### ISSUE TITLE
chart blank

### ISSUE THREAD

**Issue by ewaldheinsen** [IndyJoeA/cbpi_Tilt#5]
Hello IndieJoeA. I have been using your plugin for the Craftbeerpi3 to integrate de Tilt Hydrometer. It works fine. Reads all the hydrometers, and presents the current info. But i have trouble viewing the chart. When i pull it, it comes out blank. It does not present any historic data. Is there something I have not done? any configuration that need to be completed? most sincere appreciation for your assistance.

**Comment by 1971hemicuda** [comment]
I often find that when the chat is blank there is a read error in the log files.  Usually has to do with reading the kettle log file.  ...i wish I could say i've poked around with this but last time I had to delete my kettle and recreate it.  Then i started getting log a clean log file.  And then a chart would show up

**Comment by ewaldheinsen** [comment]
Thank you for you assistance hemicuda. I have tried resetting the kettle log file. Deleting it, and creating a new one. I get the blank chart. What i dont get is any data. Do you have re created the sensor too? did you delete it, create it new and assigne it again?

Thank you for your assistance.

**Comment by 1971hemicuda** [comment]
If you log into the terminal and head into the "logs" directory you'll see an 'app.log'.  If you look in that file you'll see what is causing the error.

I still haven't figured everything out.  I tend to just delete all my log files, reboot the system, then start my brew day.  So I have fresh logs and data.

**Comment by ewaldheinsen** [comment]
Dear hemi cuda.

Love your username, by the way. Me and a friend are fixing up his old 73
Challenger.

I figured it out. It's working. I would like to know if there is a way, in
the fermentation chamber, to visualize a chart with temp and gravity
readings from the tilt sensors. I create 2, one for the temperature and one
for the gravity. Is there a way to visualize them together? Do I need to
have the sensors created in the kettle in order for the chart to appear in
the Fermentation chamber? I have yet to test this. Will be testing
hopefully this week. Thank you in advance for all your assistance.

On Jul 6, 2018 10:20 AM, "1971hemicuda" <notifications@github.com> wrote:

If you log into the terminal and head into the "logs" directory you'll see
an 'app.log'. If you look in that file you'll see what is causing the error.

I still haven't figured everything out. I tend to just delete all my log
files, reboot the system, then start my brew day. So I have fresh logs and
data.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/IndyJoeA/cbpi_Tilt/issues/5#issuecomment-403048246>,
or mute
the thread

**Comment by Lagerman** [comment]
Running the plug in with Tilt 2.0. Connects and works great. information does not populate the chart in CBP. any updates, suggestions? Without charting, this reduces the value of the plug in to near zero.

**Comment by splitice** [comment]
I can confirm this as well. app.log shows nothing of interest either.

**Comment by splitice** [comment]
Added some debugging statements and got the following:

```
Traceback (most recent call last):
  File "/home/pi/craftbeerpi3/modules/logs/endpoints.py", line 86, in get_logs_as_json
    result = map(self.convert_chart_data_to_json, cbpi.get_fermentation_controller(fermenter.logic).get("class").chart(fermenter))
  File "/home/pi/craftbeerpi3/modules/logs/endpoints.py", line 69, in convert_chart_data_to_json
    return {"name": chart_data["name"], "data": self.read_log_as_json(chart_data["data_type"], chart_data["data_id"])}
  File "/home/pi/craftbeerpi3/modules/logs/endpoints.py", line 61, in read_log_as_json
    for row in reader:
Error: line contains NULL byte
```
